#!/bin/sh

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
CREATE USER IF NOT EXISTS '${MYSQL_DEBEZIUM_USER}'@'%' IDENTIFIED BY '${MYSQL_DEBEZIUM_PASSWORD}';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO '${MYSQL_DEBEZIUM_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
